- hosts: monitoring
  become: true
#  connection: local
#  vars:
#    - ansible_python_interpreter: /home/lur/miniconda3/envs/ansible/bin/python3
  tasks:
    - name: Install Docker
      include_role:
        name: "fabos.docker.setup"
        tasks_from: install.yml

- hosts: monitoring
  become: true
  tasks:
    - name: Install Monitoring Stack
      include_role:
        name: fabos-slm-monitoring
        tasks_from: create.yml
      vars:
        - host_registry_fqdn: "192.168.153.47"
        - host_localhost_fqdn: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        - asset_id: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
